### ISSUE TITLE
Support for extending swiss elements

### ISSUE THREAD

**Issue by kasperpihl** [swipesapp/react-swiss#9]
Thinking something like this:

```js
import { element } from 'react-swiss'
// Create the first
const Button = element('button', { color: 'blue' });

// Extend it like this
const RedButton = element(Button, {color: 'red'});
```
Also want to add the option to include styles from other elements, without extending them.
```js
// Adding another swiss element as a later parameter, should just grab the styles from it
const Input = element('input', { background: 'white' }, Button);
```

**Comment by thinklinux** [comment]
What if `Button` has `background: 'red'` but I want my `background: 'white'`? Maybe a more flexible way it's going to be something like that:

```javascript
const Input = element('input', {background: 'white'}).styles(Button, {background: 'white'});
```

In a lot of cases you are going to use this two in separate parts in the code. I don't see a reason when I am creating the element to extend it with temporary styles. It's going to be probably when I have an edge use case later in the code when I need to change a style or two. So that's another reason to have a separate method for just grabbing styles when you really need it.

**Comment by kasperpihl** [comment]
Flipping the order of the import will do that. So if you add Button first, then your override after it will work. Like here
```js
const Input = element('input', Button, { background: 'white' });
```

**Comment by thinklinux** [comment]
But then are you extending or are you just grabbing some styles? Because as I understood it earlier if it's a swiss element on the right side it's not going to extend? So this one

```javascript
const Input = element('input', Button, { background: 'white' });
```
is extending the `input`?

**Comment by kasperpihl** [comment]
First argument is always the "element" that should get rendered. So if you put 'div' as the first argument and Button as the second, it will only take the styles from Button, but still render a div.
If you however put Button as the first argument, it take both styles and whatever element Button is rendering. Very likely html 'button'-tag.

**Comment by thinklinux** [comment]
Cool, I think I get it now :))

**Comment by kasperpihl** [comment]
Added support in v0.2.7
